version: "3.1"
services:
  db:
    image: mongo:5.0.6
    container_name: egolist-crm-db
    restart: unless-stopped
    volumes:
      - ./docker/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: IlyaSharafeev
      MONGO_INITDB_ROOT_PASSWORD: Ze74790309
      MONGO_INITDB_DATABASE: CalendarDB
    ports:
      - "7017:27017"